### ISSUE TITLE
! Undefined control sequence. \CTEX@thechapter ->\CTEX@appendixnumber 

### ISSUE THREAD

**Issue by jianzhongli** [GoYchen/SYSU-LaTex-Thesis#1]
hi 师兄你好，我在尝试编译 `main.tex` 的时候遇到了一些问题，其中一处明显的报错是：

附件 log 的 2445  - 2447 行，提示 `Undefind control sequence`，`thechapter` 和 `appendixnumber` 应该是 CTeX 的命令，我的机器上也确实安装了 CTeX.  
```
(./docs/appendix1.tex
! Undefined control sequence.
\CTEX@thechapter ->\CTEX@appendixnumber 
```

Google 了一下没有得到答案。不过如果我将 `appendix1.tex` 这个文件删除，就在我的机器上成功编译 pdf. 这个文件有用到什么特别的包吗？

日志文件链接：[https://gist.github.com/kexanie/1be17fe9c8ca22f16f5d936114038bbc](https://gist.github.com/kexanie/1be17fe9c8ca22f16f5d936114038bbc)
软件版本：Windows 10, texlive 2016

**Comment by huangjj27** [comment]
遇到了同样的问题, 环境是在ubuntu16.04下面
并且搜索到了相关的信息
https://tex.stackexchange.com/questions/328842/latex-issues-undefined-control-sequence-chaptername

**Comment by huangjj27** [comment]
经过查找, 发现是`sysuthesis.cls`模板里面的300~303命令无法使用

    \gdef\CTEX@prechapter{\CTEX@appendixname}
    \gdef\CTEX@thechapter{\CTEX@appendixnumber}
    \gdef\CTEX@postchapter{}

这里无法使用的原因是因为`CTEX`宏包里面对应的一下控制变量变化了. 改成如下形式即可通过编译.
```
\gdef\CTEX@prechapter{\CTEX@preappendix}
\gdef\CTEX@thechapter{\CTEX@appendix@number}
\gdef\CTEX@postchapter{}
```

问题已经修复.

**Comment by jianzhongli** [comment]
cool，在 windows 10 + texlive 2016 下测试也可以编译通过。

**Comment by huangjj27** [comment]
希望这个快点合并更新。如果再不合并，估计我要开一个组织专门来做这个LaTeX模板了23333

**Comment by guanyingc** [comment]
师弟们好，非常感谢你们。 

不好意思啊，我最近太忙了，没看到你们的push，真的很抱歉。

这样吧，师弟们你们帮忙建一个新的repository来做个SYSU的Latex模板吧。我这个模板很不灵活而且有很多bug。希望你们可以做一个好一点的模板帮助师弟师妹们。

非常感谢！

**Comment by guanyingc** [comment]
你们可以把新建的github地址发给我，我在这个repository的Readme放上你们的地址，并提示这个repository停止维护，可以吗？

**Comment by huangjj27** [comment]
我有一个想法，把项目迁移到gitlab上的一个工作组，然后由工作组进行维护。
选用gitlab的理由是权限管理更加细致，更适合我们这种人员频繁变动的项目。

**Comment by guanyingc** [comment]
好的，非常感谢！那我把gitlab地址放在Readme上
